### ISSUE TITLE
sandbox start script isn't working 

### ISSUE THREAD

**Issue by sammychinedu2ky** [codesandbox/codesandbox-templates#134]
I created a sandbox.config.json with a startscript set to "start" , but code sandbox still runs "serve"
Please can you help me out with this?
Here is a link to my template 
https://codesandbox.io/s/docu-test-jv4ir

**Comment by andrasbacsai** [comment]
Hey, if you could restart the server as shown in the picture, I think it will work because your configurations seem OK.

![image](https://user-images.githubusercontent.com/5845193/97556336-9d255800-19d9-11eb-8b08-d1a5d608257b.png)

**Comment by sammychinedu2ky** [comment]
> Hey, if you could restart the server as shown in the picture, I think it will work because your configurations seem OK.
> 
> ![image](https://user-images.githubusercontent.com/5845193/97556336-9d255800-19d9-11eb-8b08-d1a5d608257b.png)

I did that but it didn't work. It runs yarn serve instead of yarn start

**Comment by andrasbacsai** [comment]
Hm, strange. I will investigate and let you know the outcome!

**Comment by sammychinedu2ky** [comment]
Thanks A lot 🙏for your help

**Comment by andrasbacsai** [comment]
Good to know, but I will still investigate because it should work like you used in the first place.

**Comment by sammychinedu2ky** [comment]
Ok thanks man 🙏

**Comment by andrasbacsai** [comment]
Closing this one, and I leave open the other [issue](https://github.com/codesandbox/codesandbox-client/issues/514).
